on:
  push:
    branches:
      - main

jobs:
  deploy:
    - name: Build & Deployment
    runs-on: ubuntu-latest

    steps:
      - name: get the source code
      uses: actions/checkout@v2

      - name: install Node
      uses: actions/setup-node@v2
      with:
        node-version: "12"

      - name: install project dependencies
      run: npm i

      - name: Build
      run: npm run build
      env:
        CI: false

      - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{secrets.FIREBASE_TOKEN}}