name: Firebase App Deployment

on:
  push:
    branches:
      - main
    # Run on specific files.
    paths:
    - "src/**"

# Source of this action: https://github.com/marketplace/actions/deploy-to-firebase-hosting
jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    environment: FIREBASE_SERVICE_ACCOUNT
    steps:
      - name: Get the source code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Clean install dependencies
        run: npm install

      - name: Build production bundle
        run: npm run build
        env:
          CI: false

      - name: Deploy to firebase hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_YT }}"
          projectId: yt-mimic
          channelId: live
